title: "fsx'blog"
author: "fsx"
description: "fsx's personal blog"
profilePicture: "images/fsxdesignlogo.png"
keywords: ""
favicon: "favicons/"
customCss:
  - "css/custom.css"
customJs: []
mainSections: ["post", "news", "projects"]
images: ["images/fsxdesignlogo.png"]
doNotLoadAnimations: false

singleDateFormat: "2006-01-02"
indexDateFormat: "2006-01-02"
listDateFormat: "2006-01-02"

reversepagetitle: true

math:
  enable: false